language: java
jdk:
  - openjdk8
env:
  global:
    # For maintaining the image tag based on Git Checkin SHA
    - GIT_SHA=$(git rev-parse HEAD)

before_install:
  # A] DockerHub Login
  # create the below keys (i.e. DockerHub credentials) in the Travis CLI Project -> More Options -> Settings -> Environment Variables
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_ID" --password-stdin 
  - echo ">> docker login successful."

# to disable the default installation routine of maven commands  
install: true
script: 
  # B] Maven Build & Docker Image Push
  - mvn clean package 
  - mvn dockerfile:build
  - mvn dockerfile:tag@tag-version -Dgit-sha-tag=$GIT_SHA
  - mvn dockerfile:push@push-latest
  - mvn dockerfile:push@push-version 
  - echo ">> maven build and dockerhub push successful."
  

# NOTE: cache the build tool's repository
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle 
