language: java
jdk:
  - openjdk8


before_install:
  # A] DockerHub Login
  # create the below keys (i.e. DockerHub credentials) in the Travis CLI Project -> More Options -> Settings -> Environment Variables
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_ID" --password-stdin 
  - echo ">> docker login successful."

# to disable the default installation routine of maven commands  
install: true
script: 
  # B] Maven Build & Docker Image Push
  - mvn clean package dockerfile:push
  - echo ">> maven build and dockerhub push successful."
  

# NOTE: cache the build tool's repository
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle 
